services:
  - type: web
    name: predictive-backend
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app
    pythonVersion: 3.10
    rootDir: backend

  - type: web
    name: predictive-frontend
    env: static
    buildCommand: npm install && npm run build
    staticPublishPath: dist
    rootDir: frontend