services:
  - type: web
    name: predictive-backend
    env: python
    buildCommand: |
      curl -sSL https://install.python-poetry.org | python3 -
      poetry env use python3.10
      pip install -r requirements.txt
    startCommand: gunicorn app:app
    rootDir: backend

  - type: web
    name: predictive-frontend
    env: static
    buildCommand: npm install && npm run build
    staticPublishPath: dist
    rootDir: frontend